In [1]:
import pyodbc
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Información de la base de datos
server = 'ROBLEDO'
db = 'Maraton'

# Nos conectamos a la base de datos con SQL Server
try:
    connection = pyodbc.connect(driver='{SQL server}', host=server, database=db)
    print('Conexión exitosa')
except:
    print('Error de conexión')

Conexión exitosa

In [3]:
# Consulta a la base de datos
cursor = connection.cursor()
cursor.execute(
    """
    SELECT *
    FROM Maraton_NY
    """
)

# Extrae una lista de tuplas
tabla = cursor.fetchall()

# Cerrar el cursor y la conexión de la base de datos
cursor.close()
connection.close()

In [4]:
import numpy as np

array = np.asarray(tabla)
headers = ['corredor', 'place', 'gender', 'age', 'home', 'time']
df = pd.DataFrame(array, columns=headers)
df.head()

  corredor  place  gender age home        time
0     3475   3592    Male  52  GBR  217.483337
1    13594  13853  Female  40   NY  272.549988
2    12012  12256    Male  31  FRA  265.283325
3    10236  10457  Female  33   MI  256.149994
4     9476   9686    Male  33   NY      252.25

In [5]:
# Ordenar por edad
df = df.replace('None', np.nan)
df.sort_values(by='age').head()

    corredor  place  gender age  home        time
249    18260  18589    Male   5  None  302.683319
115    23003  23373    Male  18   MEX  408.333344
206    14984  15257  Female  20    CA  278.799988
801    19763  20101  Female  20    PA  310.049988
272    22746  23115  Female  20   GBR  387.399994

In [6]:
# Datos faltantes
df.isnull().sum()

corredor    0
place       0
gender      0
age         0
home        1
time        0
dtype: int64